all:
  vars:
    ansible_user: root
  children:
    k8s_cp_bootstrap:
      hosts:
        k8s-cp-01:
          ansible_host: 192.168.2.19

    k8s_control_plane:
      hosts:
        k8s-cp-01:
          ansible_host: 192.168.2.19
        k8s-cp-02:
          ansible_host: 192.168.2.21
        k8s-cp-03:
          ansible_host: 192.168.2.20

    k8s_workers:
      hosts:
        k8s-wkr-01:
          ansible_host: 192.168.2.22
        k8s-wkr-02:
          ansible_host: 192.168.2.23
        k8s-wkr-03:
          ansible_host: 192.168.2.24

    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
